/*
 * Tencent is pleased to support the open source community by making xLua available.
 * Copyright (C) 2016 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 * http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

using System.Collections.Generic;
using System;
using UnityEngine;
using XLua;
using wc.framework;
using UnityEngine.U2D;
using UnityEngine.UI;

//using System.Reflection;
//using System.Linq;

//配置的详细介绍请看Doc下《XLua的配置.doc》
public static class ExampleGenConfig
{
    //lua中要使用到C#库的配置，比如C#标准库，或者Unity API，第三方库等。
    [LuaCallCSharp]
    public static List<Type> LuaCallCSharp = new List<Type>() {
                typeof(System.Object),
                typeof(UnityEngine.Object),
                typeof(Vector2),
                typeof(Vector3),
                typeof(Vector4),
                typeof(Quaternion),
                typeof(Color),
                typeof(Ray),
                typeof(Bounds),
                typeof(Ray2D),
                typeof(Time),
                typeof(GameObject),
                typeof(Component),
                typeof(Behaviour),
                typeof(Transform),
                typeof(Resources),
                typeof(TextAsset),
                typeof(Keyframe),
                typeof(AnimationCurve),
                typeof(AnimationClip),
                typeof(Animation),
                typeof(MonoBehaviour),
                typeof(ParticleSystem),
                typeof(SkinnedMeshRenderer),
                typeof(Renderer),
                typeof(Material),
                typeof(Shader),
                typeof(WWW),
                // typeof(TweenTool),
                // typeof(TweenEaseType),
                typeof(Mathf),
                typeof(System.Collections.Generic.List<int>),
                typeof(Action<string>),
                typeof(UnityEngine.Debug),
                typeof(UnityEngine.SystemInfo),
                typeof(UnityEngine.UI.Button),
                typeof(UnityEngine.UI.Toggle),
                typeof(UnityEngine.UI.Text),
                // typeof(EmojiText),
                typeof(UnityEngine.UI.Image),
                // typeof(PoolManager),
                typeof(UnityEngine.AnimatorUpdateMode),
                // typeof(HttpRequest),
                // typeof(CustomDebugger),
                // typeof(CameraShake),
                // typeof(CameraController),
                // typeof(AutoPlay),
                // typeof(AxisConstraint),
                // typeof(Ease),
                // typeof(LogBehaviour),
                // typeof(LoopType),
                // typeof(PathMode),
                // typeof(PathType),
                typeof(FileHelper),
                typeof(AssetsManager),
                typeof(ManifestManager),
                typeof(BundleManager),
                typeof(BundleObject),
                // typeof(PhysicsTool),
                // typeof(RotateMode),
                // typeof(ScrambleMode),
                // typeof(TweenType),
                // typeof(UpdateType),
                // typeof(DOTween),
                // typeof(DOVirtual),
                // typeof(EaseFactory),
                // typeof(Tweener),
                // typeof(Tween),
                // typeof(Sequence),
                // typeof(TweenParams),
                // typeof(VectorHelper),
                // typeof(DG.Tweening.Core.ABSSequentiable),
                // typeof(DG.Tweening.Core.TweenerCore<Vector3, Vector3, DG.Tweening.Plugins.Options.VectorOptions>),
                // typeof(TweenCallback),
                // typeof(TweenExtensions),
                // typeof(TweenSettingsExtensions),
                // typeof(ShortcutExtensions),
                // typeof(LuaTransformHelper),
                // typeof(LineRenderer),
                // typeof(LineControl),
                // typeof(LoopScrollView),
                // typeof(OutlineEx),
                // typeof(AudioHelper),
                typeof(RectTransform),
                typeof(Application),
                // typeof(Rigidbody),
                // typeof(ChatClient),
                // typeof(CmdBuffer),
                // typeof(HollowOutMask),
                // typeof(LoopListView2),
                // typeof(DelayPlay),
                // typeof(EffectTime),
                typeof(UnityEngine.UI.VerticalLayoutGroup),
                // typeof(UIFontController),
                // typeof(MiGongPingTai),
                // typeof(MiGongQiao),
                // typeof(MiGongYun),
                typeof(Canvas),
                typeof(RenderSettings),
                // typeof(SceneGuide_Tianji),
                typeof(Animator),
                typeof(AnimationClip),
                // typeof(Curve3),
                // typeof(ShakeCurve),
                // typeof(GameOverMove),
                // typeof(RuntimeAnimatorController),
                // typeof(SdkComponent),
                // typeof(SDKHelper),
                // typeof(StatisticsHelper),
                // typeof(WhaleSdkHelper),
                // typeof(PlatformUtil),
                // typeof(zmhx.SceneManager),
                // typeof(zmhx.PlayerLuaViewHelper),
                // typeof(zmhx.PlayerLuaAnimator),
                // typeof(zmhx.PlayerLuaUI),
                // typeof(zmhx.PlayerLuaEffect),
                // typeof(zmhx.HpBar),
                // typeof(zmhx.FootUI),
                // typeof(zmhx.PlayerTalk),
                // typeof(zmhx.EffectManager),
                // typeof(zmhx.TimeManager),
                // typeof(zmhx.PlayerLine),
                // typeof(zmhx.PhoneHelper),
                // typeof(GameObjectClickMgr),
                // typeof(LuaArrAccess),
                // typeof(LuaArrAccessAPI),
                // typeof(LuaGameLaunch),
                // typeof(VideoControl),
                // typeof(AssetLoaderHelper),
                // typeof(AssetBundleHelper),
                // typeof(AssetObject.AssetObjectLoadedCallBack),
                // typeof(SRFileUtil),
                // typeof(SceneEventConfigTrigger),
                // typeof(WorldSceneLuaBehaiour),
                // typeof(WorldCamera),
                // typeof(LuaGameObjectUpdater),
                // typeof(PlayerPrefs),
                // typeof(ScreenShot),
                // typeof(Scene3DObjectClickHelper),
                // typeof(Game3DUI),
                // typeof(GameRoleController),
                // typeof(DOTweenAnimation),
                // typeof(DragEventHelper),
                // //typeof(FogOfWarEffect),
                // typeof(RawImageLoadSet),
                // typeof(LuaZipHelper),
                // typeof(ResourcesHelper),
                // typeof(PingTaiQiaoManager),
                // typeof(RotationToPlayer),
                // typeof(GrayToColor),
                // typeof(WuXingZhenCamera),
                // typeof(ArrowForward),
                // typeof(GridLayoutGroup),
                // typeof(TextAnchor),
                // typeof(ScrollRectClick),
                // typeof(LoginCamera),
                // //typeof(GMSDKGPM),
                // typeof(TimeLinePlay),
                // typeof(JuBaoShan3DUI),
                // typeof(XianControll),
                // typeof(FollowUI),
                // typeof(UGUISpriteAnimation),
                // typeof(LoaderUpdate),
                // typeof(Mole_Manager),
                // typeof(AppAdvisory.StopTheLock.GameManager),
                // typeof(AppAdvisory.StopTheLock.DotPosition),
                // typeof(PairsGameManager),
                // typeof(TableLevel),
                // typeof(MainCtrl),
                // typeof(GameView),
                // typeof(SharePicture),
                // typeof(SharePoster),
                typeof(GC),
                // typeof(AppRatingController),
                // typeof(AutoUnloadAB),

    };

    //C#静态调用Lua的配置（包括事件的原型），仅可以配delegate，interface
    [CSharpCallLua]
    public static List<Type> CSharpCallLua = new List<Type>() {
                typeof(Action),
                typeof(Action<SpriteAtlas>),
                typeof(Func<LuaTable, int>),
                typeof(Func<double, double, double>),
                typeof(Func<LuaTable,string, LuaTable>),
                typeof(Action<string>),
                typeof(Action<double>),
                typeof(Action<int>),
                typeof(Action<float>),
                typeof(Action<int,int,GameObject>),
                typeof(Action<bool,string,string>),
                typeof(Action<bool,string,string,long>),
                typeof(Action<bool, byte[], string, long>),
                typeof(Action<string,long>),
                typeof(Action<long,long>),
                typeof(Action<int,int>),
                typeof(Action<bool,int>),
                typeof(Action<float,float>),
                typeof(Action<int, float, float>),
                typeof(Action<GameObject, string, int>),
                typeof(UnityEngine.Events.UnityAction),
                typeof(UnityEngine.Events.UnityAction<bool>),
                typeof(UnityEngine.Events.UnityAction<Vector2>),
                typeof(System.Collections.IEnumerator),
                // typeof(Action<LoopScrollView, int, int, GameObject>),
                // typeof(System.Func<LoopListView2, int, LoopListViewItem2>),
                typeof(Action<string,string>),
                typeof(Action<byte[]>),
            };

    //黑名单
    [BlackList]
    public static List<List<string>> BlackList = new List<List<string>>()  {
                new List<string>(){"System.Xml.XmlNodeList", "ItemOf"},
                new List<string>(){"UnityEngine.WWW", "movie"},
    #if UNITY_WEBGL
                new List<string>(){"UnityEngine.WWW", "threadPriority"},
    #endif
                new List<string>(){"UnityEngine.Texture2D", "alphaIsTransparency"},
                new List<string>(){"UnityEngine.Security", "GetChainOfTrustValue"},
                new List<string>(){"UnityEngine.CanvasRenderer", "onRequestRebuild"},
                new List<string>(){"UnityEngine.Light", "areaSize"},
                new List<string>(){"UnityEngine.Light", "lightmapBakeType"},
                new List<string>(){"UnityEngine.WWW", "MovieTexture"},
                new List<string>(){"UnityEngine.WWW", "GetMovieTexture"},
                new List<string>(){"UnityEngine.AnimatorOverrideController", "PerformOverrideClipListCleanup"},
    #if !UNITY_WEBPLAYER
                new List<string>(){"UnityEngine.Application", "ExternalEval"},
    #endif
                new List<string>(){"UnityEngine.GameObject", "networkView"}, //4.6.2 not support
                new List<string>(){"UnityEngine.Component", "networkView"},  //4.6.2 not support
                new List<string>(){"System.IO.FileInfo", "GetAccessControl", "System.Security.AccessControl.AccessControlSections"},
                new List<string>(){"System.IO.FileInfo", "SetAccessControl", "System.Security.AccessControl.FileSecurity"},
                new List<string>(){"System.IO.DirectoryInfo", "GetAccessControl", "System.Security.AccessControl.AccessControlSections"},
                new List<string>(){"System.IO.DirectoryInfo", "SetAccessControl", "System.Security.AccessControl.DirectorySecurity"},
                new List<string>(){"System.IO.DirectoryInfo", "CreateSubdirectory", "System.String", "System.Security.AccessControl.DirectorySecurity"},
                new List<string>(){"System.IO.DirectoryInfo", "Create", "System.Security.AccessControl.DirectorySecurity"},
                new List<string>(){"UnityEngine.MonoBehaviour", "runInEditMode"},
                new List<string>(){"UnityEngine.UI.Text", "OnRebuildRequested"},
            };
}
